[package]
name = "tankvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.1"
crossterm = "0.25.0"
libc = "0.2.134"
terminal-keycode = "1.1.1"
